# Generated by Django 4.0.3 on 2022-03-17 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('rate', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('by_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_by', to='client.client')),
                ('to_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_client', to='client.client')),
                ('to_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_recipe', to='recipe.recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentrate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('to_client__isnull', False), ('to_recipe', None)), models.Q(('to_client', None), ('to_recipe__isnull', False)), _connector='OR'), name='not_both_null'),
        ),
    ]
