# Generated by Django 4.0.3 on 2022-03-17 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=400)),
                ('confirmed', models.CharField(choices=[('D', 'Delete'), ('S', 'On Stage Yet'), ('A', 'Add')], default='S', max_length=2)),
                ('client_rated_recipe', models.PositiveIntegerField(blank=True, default=0)),
                ('overall_stars', models.PositiveIntegerField(blank=True, default=0)),
                ('overall_understood', models.PositiveIntegerField(blank=True, default=0)),
                ('clearness_votes', models.PositiveIntegerField(blank=True, default=0)),
                ('by_cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('ingredients', models.ManyToManyField(blank=True, to='ingredients.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('description', models.CharField(max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_of_recipe', to='recipe.recipe')),
            ],
        ),
    ]
